### ISSUE TITLE
Requesting to check SN 162 in DIP report

### ISSUE THREAD

**Issue by sagunkc-hki** [hispindia/DHIS2-HKI#10]
SN 162 in DIP shows following no.:

162 | Output 4.1.2 | 162-Support   to  capacitate VDC/Municipality level Nutrition and Food Security   Steering Committee meetings | 1-# of meeting   conducted |   | 57

I tried to generate data from Pivot app and it's showing 41.

Please confirm.

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

Please check now, value should match.

**Comment by sagunkc-hki** [comment]
It matches to 51 now.
this, however, is a completely different number. 
what was the issue?
