### ISSUE TITLE
Dashboards required on LIVE system

### ISSUE THREAD

**Issue by sagunkc-hki** [hispindia/DHIS2-HKI#3]
We need to generate atlest DIP report urgently for year 1 progress report. Need this report on LIVE system dashboard urgently. If possible, please also add IR-wise filter too.

**Comment by Saurabhhisp** [comment]
@sagunkc-hki Dashboard has been added on live server. (Dashboard 04)

Please check the access, has been shared with DC, PNGO and HKI User groups.

We are testing the report for the data efficacy, will update if any changes are foreseen.
