### ISSUE TITLE
Requesting remaining dashboards on LIVE system for review

### ISSUE THREAD

**Issue by sagunkc-hki** [hispindia/DHIS2-HKI#6]
@Saurabh,
We are compiling feedbacks on developed dashboards.
It'll be helpful if you can share the dashboards and reports developed so far to the hki user group.

**Comment by sagunkc-hki** [comment]
Hi Saurabh,
Still waiting for the dashboards in live system.
the ones we saw in test system were very preliminary and requires a lot of changes.
please transfer development so far to the live system so that we can provide our feedback.

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

On the live system, at present the data import from Commcare is in progress, and is being tested for efficacy.

In order for us to start putting up dashboards, it will be important to understand the feedback on the preliminary dashboards, which were default dashboard available in DHIS2.

Please send us the feedback based on the preliminary release, in terms of what visualization is preferred in comparison to what was presented. 

The feedback will help us define the approach, if any custom development is required to develop the same.

Once we go through the feedback, we can start discussion on the design from next week and start iterative process of demonstration and feedback.

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

test version of the dashboards can be accessed here for providing feedback.

http://apps.hispindia.org/suaahara2/dhis-web-commons/security/login.action

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

Awaiting feedback please! Can we call regarding the same?

Please suggest date and time as per your convenience.

**Comment by sagunkc-hki** [comment]
@ saurabh,
Can you please turn the server back on. 
We're trying to review the dashboards.

Thank You

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

Working now, please check!

**Comment by sagunkc-hki** [comment]
it's working now.
thank you

**Comment by sagunkc-hki** [comment]
@ saurabh
The system is accessible but the dashboards are not there. 
Please check and fix.

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

Please check now, have put the training database back.

**Comment by sagunkc-hki** [comment]
Got it. Thanks.

**Comment by sagunkc-hki** [comment]
Hi Saurabh. 
Can you please turn it back online again.
Thanks

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

Hi Sagun, its working now please check.

**Comment by sagunkc-hki** [comment]
thank you
