### ISSUE TITLE
DIP report removed from the dashboard

### ISSUE THREAD

**Issue by sagunkc-hki** [hispindia/DHIS2-HKI#8]
DIP report has been removed from the dashboard since yesterday afternoon. 
Please ensure the integrity of the system when any updates are made.

**Comment by sagunkc-hki** [comment]
This is the second time the DIP report is removed from the dashboard. Please fix.

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

The members from HKI user group have the authority other than us to remove the report.

We have not removed the report last 2 times, please make sure it is not happening at your end.

Please ask the users not to click on the 'Remove' button on the dashboard block.

Report has been added again.
