### ISSUE TITLE
Query on DIP report update

### ISSUE THREAD

**Issue by sagunkc-hki** [hispindia/DHIS2-HKI#9]
how's this report generated? are the numbers updated instantly upon data entry or needs to run data analytics??

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

Standard reports work on data analytics, analytics engine need to run to add on latest data entered. As of now it is running on a 2 hourly basis.

We have been testing report from Jan 16 to June 17. Is the data entry still in progress for June 2017 or it has been completed?

**Comment by sagunkc-hki** [comment]
We're still modifying some numbers. Can you tell me how to trigger analytics engine manually?

**Comment by Saurabhhisp** [comment]
Alright.

Go to reports, on the left hand side, there is a menu item 'Analytics', click on that, on next page click on 'Export'

**Comment by sagunkc-hki** [comment]
Requesting check. I updated the number on HKI Meeting Center Semi-Annual data set in the following activity and run analytics. The DIP report not updated. Please verify 

PM output | 1-Project Advisory Group Meeting | 1-# of project avdisor group meeting conducted | 2 | 0

**Comment by Saurabhhisp** [comment]
Value is coming as 1 under Project advisor group meeting conducted for period Jan 2016 to June 2017.

Please confirm if you have added 1. 

Clear the cache before generating the report again.

Report attached for reference.

[DIP 17th July.xls.xlsx](https://github.com/hispindia/DHIS2-HKI/files/1151972/DIP.17th.July.xls.xlsx)

**Comment by sagunkc-hki** [comment]
cache cleared. still 0 at my end. weird
